name: dramatoons_front_staging

services:
  front:
    build:
      context: .
      target: prod
      args:
        - VITE_API_URL=https://api-staging.dramatoons.ovh
        - VITE_STAGING_AUTH=${VITE_STAGING_AUTH}