services:
  front:
    build:
      context: .
    restart: unless-stopped
    networks:
      - global_proxy_network
    environment:
      - VITE_API_URL=http://localhost:8081
      - AUTH_TYPE=off

networks:
  global_proxy_network:
    external: true