name: dramatoons_front_staging

services:
  front:
    build:
      context: .
      target: prod
      args:
        - VITE_API_URL=https://api-staging.dramatoons.ovh
        - AUTH_TYPE="Accès Restreint Staging"
      volumes:
        - /etc/nginx/.htpasswd:/etc/nginx/.htpasswd:ro