services:
  front:
    build:
      context: .
    container_name: dramatoons_front
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - api_internal_network
    environment:
      - VITE_API_URL=http://localhost:8081

networks:
  api_internal_network:
    external: true
    name: shared_api_network

volumes:
  dramatoons_front_data: