server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;

        auth_basic $auth_type;
        auth_basic_user_file /etc/nginx/.htpasswd;
    }
}